
name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_messaging: ^15.0.2
  firebase_app_check: ^0.3.0+2
  
  # State Management & UI
  provider: ^6.1.2
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1

  # Agora - UPGRADED
  agora_rtc_engine: ^6.3.2 # Upgraded to the latest stable version
  agora_token_service: ^0.1.0 # For generating Agora tokens
  
  # Utilities
  permission_handler: ^11.3.1
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
