// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApA_k-B9F3gDxEZiVuGpmJDajHjlztQZg',
    appId: '1:189355303657:android:a4bd1a0a898df46df28678',
    messagingSenderId: '189355303657',
    projectId: 'tr335-videochat',
    databaseURL: 'https://tr335-videochat-default-rtdb.firebaseio.com',
    storageBucket: 'tr335-videochat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9B6Ugk5L-3uodMFAExIhVTiD7R7thcqo',
    appId: '1:189355303657:ios:2ea9cb9649c5637cf28678',
    messagingSenderId: '189355303657',
    projectId: 'tr335-videochat',
    databaseURL: 'https://tr335-videochat-default-rtdb.firebaseio.com',
    storageBucket: 'tr335-videochat.firebasestorage.app',
    iosBundleId: 'com.connect.videochat.messaging.realtime',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP1jVennognT3a5Zmbewvdjbg-4kyO3xk',
    appId: '1:189355303657:web:1870105c36bba4cbf28678',
    messagingSenderId: '189355303657',
    projectId: 'tr335-videochat',
    authDomain: 'tr335-videochat.firebaseapp.com',
    databaseURL: 'https://tr335-videochat-default-rtdb.firebaseio.com',
    storageBucket: 'tr335-videochat.firebasestorage.app',
    measurementId: 'G-31Z4PWFX03',
  );

}